/* ============================================================================
   TSIGOURA VERDE — published menu
   ----------------------------------------------------------------------------
   This file IS the live menu. It is generated by the admin panel:
       /admin  →  Ρυθμίσεις  →  "Κατέβασμα menu-live.js"
   Replace this file in the project, redeploy, and every phone shows the change.

   While TV_MENU_STATE is null the built-in catalogue in tsigoura-data.js is used.
   ========================================================================== */
window.TV_MENU_STATE = null;
window.TV_MENU_PUBLISHED_AT = '';
